services:
  airlock:
    image: docker-proxy.opensafely.org/opensafely-core/airlock:latest
    container_name: airlock
    init: true
    restart: unless-stopped
    network_mode: bridge
    logging:
      driver: journald
      options:
        tag: airlock
    ports:
      - "443:8000"
    user: 10000:10000
    dns: 127.0.0.1  # disable dns, as there's no resolver running inside the container
    env_file:
      - /home/opensafely/config/01_defaults.env
      - /home/opensafely/config/02_secrets.env
      - /home/opensafely/config/03_backend.env
      - /home/opensafely/config/04_local.env
    environment:
      AIRLOCK_WORK_DIR: /workdir/
      AIRLOCK_WORKSPACE_DIR: /workspaces/
      AIRLOCK_REQUEST_DIR: /requests/
      DJANGO_DEBUG: "False"
    command: gunicorn --config gunicorn.conf.py --certfile /certs/airlock.crt --keyfile /certs/airlock.key airlock.wsgi
    volumes:
      - /home/opensafely/airlock/workdir:/workdir
      - /srv/medium_privacy/workspaces:/workspaces:ro
      - /srv/medium_privacy/requests:/requests
      - ./certs:/certs
      # use our hardcoded DNS
      - /etc/hosts:/etc/hosts:ro
      # map opensafely user/group/uid/gid info from host. Supresses confusing
      # error message.
      # Note: this is *required* for run-one-constantly to work
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

