#!/bin/bash
# Do *not* set -eu, as this is source *into* a shell

if groups | grep -q developers; then
    echo "You are logged in under your personal username."
    echo ""
    echo "To operate OpenSAFELY services, please switch to the shared opensafely user:"
    echo ""
    echo "  sudo su - opensafely"
    echo ""
fi
