#!/bin/bash
# load config into this shell so we can just run stuff
set -a
# shellcheck disable=SC1090
for f in /srv/jobrunner/environ/*.env; do
    . "$f"
done
set +a

# let jobrunner user use the jobrunner commands and scripts easily
export PYTHONPATH=/srv/jobrunner/code:/srv/jobrunner/lib
export PATH=$PATH:/srv/jobrunner/code/scripts

cat << EOF
You have logged into the shared jobrunner account for managing the jobrunner service.

Current status:

systemctl status -n0 jobrunner
$(systemctl status -n0 jobrunner)

Environment variables have been set from /srv/jobrunner/environ/*.env"

Code: /srv/jobrunner/code
Deps: /srv/jobrunner/lib
Config: /srv/jobrunner/environ

Medium privacy files are at $MEDIUM_PRIVACY_STORAGE_BASE
High privacy files are at $HIGH_PRIVACY_STORAGE_BASE

To restart:

    sudo systemctl restart jobrunner

Please consult ~/playbook.md for operational documentation.
EOF
