#!/bin/bash
# run release-hatch tests
docker-compose -f ~jobrunner/release-hatch/docker-compose.yaml run --rm release-hatch-test

# check CORS preflight
curl -s --fail https://localhost -X OPTIONS \
  -H 'Access-Control-Request-Method: GET' \
  -H 'Access-Control-Request-Headers: authorization' \
  -H 'Origin: https://jobs.opensafely.org' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Dest: empty'
