#!/bin/bash
# run release-hatch tests
docker-compose -f ~jobrunner/release-hatch/docker-compose.yaml exec -T release-hatch python hatch/client.py test


# check CORS preflight
curl -s --fail localhost:8001 -X OPTIONS \
  -H 'Access-Control-Request-Method: GET' \
  -H 'Access-Control-Request-Headers: authorization' \
  -H 'Origin: https://jobs.opensafely.org' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Dest: empty'
