services:
  jobrunner:
    image: docker-proxy.opensafely.org/opensafely-core/job-runner:latest
    container_name: jobrunner
    init: true
    restart: unless-stopped
    network_mode: bridge
    logging:
      driver: journald
      options:
        tag: jobrunner
    user: 10000:10000
    # run as the the current user to preserve file permissions
    group_add: ["${DOCKER_HOST_GROUPID}"]
    dns: 127.0.0.1  # disable dns, as there's no resolver running inside the container
    env_file:
      - /home/opensafely/config/01_defaults.env
      - /home/opensafely/config/02_secrets.env
      - /home/opensafely/config/03_backend.env
      - /home/opensafely/config/04_local.env
    volumes:
      # these paths must be absolute on the host, and must be mount to the
      # identical absolute paths inside the container. This allows for
      # job-runner to use the same value for both its own file access, and for
      # what to pass to the host docker as a bindmount source directory, which
      # needs to be on the host. 
      # We can potentially fix this by adding an explicit bind mount source configs, if we want to
      # Note: we cannot interpolate the multiple envfiles here, so we have to hard code these paths.
      - /srv/high_privacy:/srv/high_privacy
      - /srv/medium_privacy:/srv/medium_privacy
      - /home/opensafely/jobrunner/workdir:/workdir
      # docker control
      - /var/run/docker.sock:/var/run/docker.sock
      # use the default dev workdir
      # use our hardcoded DNS
      - /etc/hosts:/etc/hosts:ro
      # used to avoid ugly uid/gid lookup failures, but not strictly required
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    environment:
      # default dev config
      WORKDIR: /workdir
      # force using mounted docker socket
      DOCKER_HOST: unix:///var/run/docker.sock
