#!/bin/bash
set -euo pipefail

# Set up the job-runner service
SRC_DIR=services/jobrunner
BACKEND_SRC_DIR=backends/$1
HOME_DIR=/home/jobrunner

# set default file creation permission for this script be 640 for files and 750
# for directories
umask 027


# ensure shared user is set up properly
if id -u jobrunner 2>/dev/null; then
    # ensure jobrunner is in docker group
    usermod -a -G docker jobrunner
    # ensure jobrunner group ids
    usermod -u 10000 jobrunner
    groupmod -g 10000 jobrunner
else
    useradd jobrunner --create-home --shell /bin/bash --uid 10000 -G docker
fi

copy_with_warning() {
    local src=$1
    local dst=$2

    test -f "$dst" && cp "$dst" "$dst.bak"

    cat > "$dst" << EOF
# DO NOT EDIT THIS FILE MANUALLY!
#
# It is automatically updated by the infrastructure code.
#
# Add any local overrides to into $local_env
#
EOF
    cat "$src" >> "$dst"
}

# set up config

mkdir -p $HOME_DIR/config
defaults_env="$HOME_DIR/config/01_defaults.env"
secrets_env="$HOME_DIR/config/02_secrets.env"
backend_env="$HOME_DIR/config/03_backend.env"
local_env="$HOME_DIR/config/04_local.env"

copy_with_warning $SRC_DIR/defaults.env "$defaults_env"
copy_with_warning "$BACKEND_SRC_DIR/backend.env" "$backend_env"

# TODO: test for new secrets in template not in env?
test -f $secrets_env || cp $SRC_DIR/secrets-template.env $secrets_env
chmod 0600 $secrets_env

# make sure local env exists
test -f "$local_env" || echo "# add local overrides here (this file is safe to edit by hand)" > "$local_env"

# utility for injecting test config
if test -f "${TEST_CONFIG:-}"; then
    cat "$TEST_CONFIG" >>"$local_env"
fi

# update playbook
# explicitly remove it first, in case it's a symlink to an old location
rm -f $HOME_DIR/playbook.md
cp playbook.md $HOME_DIR/playbook.md
# clean up old playbook if present
rm -f /srv/playbook.md

