#!/bin/bash
# this script is designed to be sourced from other scripts

# function to load and set out environment config
load-env() {
    # load config into this shell so we can just run stuff
    set -a
    # shellcheck disable=SC1090
    for f in /home/opensafely/config/*.env; do
        . "$f"
    done
    set +a
}

load-env
