#!/bin/bash
set -euo pipefail

CONFIG_SRC_DIR=config
BACKEND_SRC_DIR=backends/$1
HOME_DIR=/home/opensafely
CONFIG_DIR=$HOME_DIR/config
SECRET_DIR=$HOME_DIR/secret

# set default file creation permission for this script be 640 for files and 750
# for directories
umask 027


copy_with_warning() {
    local src=$1
    local dst=$2

    test -f "$dst" && cp "$dst" "$dst.bak"

    cat > "$dst" << EOF
# DO NOT EDIT THIS FILE MANUALLY!
#
# It is automatically updated by the infrastructure code.
#
# Add any local overrides to into $local_env
#
EOF
    cat "$src" >> "$dst"
}

# set up config

mkdir -p $CONFIG_DIR $SECRET_DIR
defaults_env="$HOME_DIR/config/01_defaults.env"
secrets_env="$HOME_DIR/config/02_secrets.env"
backend_env="$HOME_DIR/config/03_backend.env"
local_env="$HOME_DIR/config/04_local.env"

copy_with_warning $CONFIG_SRC_DIR/defaults.env "$defaults_env"
copy_with_warning "$BACKEND_SRC_DIR/backend.env" "$backend_env"

# TODO: test for new secrets in template not in env?
test -f $secrets_env || cp $CONFIG_SRC_DIR/secrets-template.env $secrets_env

# make sure local env exists
test -f "$local_env" || echo "# add local overrides here (this file is safe to edit by hand)" > "$local_env"

# utility for injecting test config
if test -f "${TEST_CONFIG:-}"; then
    cat "$TEST_CONFIG" >>"$local_env"
fi

# copy in helper script
cp scripts/load-env $HOME_DIR/config/load-env

# ensure restricted permissions
chown -R opensafely:opensafely $CONFIG_DIR $SECRET_DIR
chmod 0700 $CONFIG_DIR $SECRET_DIR
find $CONFIG_DIR $SECRET_DIR -type f -exec chmod 0600 {} \;
