name: Run tests

on:
  push: 
  workflow_dispatch:
  schedule:
    # run daily at 2:22am
    - cron: "22 02 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Run lint
    steps:
    - name: Install lint dependencies
      run: sudo apt-get install -y shellcheck
    - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run lint
      run: just tests/lint
  tests:
    strategy:
      fail-fast: false
      matrix:
        backend_name: ['test', 'tpp']
    runs-on: ubuntu-20.04
    name: Tests tests
    steps:
    - name: Set up LXD
      run: |
        # sometimes autorefresh blocks this, so let it finish updating and try again, once.
        sudo snap set lxd shiftfs.enable=true || { sleep 10 && sudo snap set lxd shiftfs.enable=true; }
        sudo lxd init --auto
        sudo lxc info
    - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare test image & testuser key
      run: just tests/build
    - name: Run tests
      run: just tests/run_test tests/backends/${{ matrix.backend_name }}.sh
