name: Run tests

on:
    push: 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run lint and tests tests
    steps:
    - name: Set up LXD
      run: |
        sudo snap set lxd shiftfs.enable=true | { sleep 20 && sudo snap set lxd shiftfs.enable=true; }
        sudo lxd init --auto
        sudo lxc info
    - name: Install test depenencies
      run: sudo apt-get install -y shellcheck
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run lint
      run: make lint
    - name: Prepare test image
      # -E so that we get the github environment, e.g. GITHUB_ACTIONS, which we use to switch behaviour
      run: sudo -E make test-image
    - name: Run tests
      run: sudo -E make test
