name: Run tests

on:
    push: 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Run lint
    steps:
    - name: Install lint dependencies
      run: sudo apt-get install -y shellcheck
    - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run lint
      run: just lint
  tests:
    strategy:
      fail-fast: false
      matrix:
        backend_name: ['emis']
    runs-on: ubuntu-20.04
    name: Tests tests
    steps:
    - name: Set up LXD
      run: |
        # sometimes autorefresh blocks this, so let it finish updating and try again, once.
        sudo snap set lxd shiftfs.enable=true || { sleep 10 && sudo snap set lxd shiftfs.enable=true; }
        sudo lxd init --auto
        sudo lxc info
    - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare test image & testuser key
      run: just build
    - name: Run tests
      run: just run_test tests/${{ matrix.backend_name }}-backend.sh
