name: Run tests

on:
    push: 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  tests:
    runs-on: ubuntu-20.04
    name: Run lint and tests tests
    steps:
    - name: Set up LXD
      run: |
        # sometimes autorefresh blocks this, so let it finish updating and try again, once.
        sudo snap set lxd shiftfs.enable=true || { sleep 10 && sudo snap set lxd shiftfs.enable=true; }
        sudo lxd init --auto
        sudo lxc info
    - name: Install test depenencies
      run: sudo apt-get install -y shellcheck
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run lint
      run: make lint
    - name: Prepare test image
      # -E so that we get the github environment, e.g. GITHUB_ACTIONS, which we use to switch behaviour
      run: sudo -E make test-image
    - name: Run tests
      run: sudo -E make test
