name: Run tests

on:
  push: 
  workflow_dispatch:
  schedule:
    # run daily at 2:22am
    - cron: "22 02 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Run lint
    steps:
    - name: Install lint dependencies
      run: sudo apt-get install -y shellcheck
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # 3.0.0
    - name: Checkout
      uses: actions/checkout@v5
    - name: Run lint
      run: just tests/lint
  tests:
    name: Tests tests
    strategy:
      fail-fast: false
      matrix:
        backend_name: ['test', 'tpp']
    runs-on: ubuntu-22.04
    steps:
    - name: Setup lxd
      uses: canonical/setup-lxd@a3c85fc6fb7fff43fcfeae87659e41a8f635b7dd # 0.1.3
      with:
        channel: latest/stable
    - name: Setup just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # 3.0.0
    - name: Checkout
      uses: actions/checkout@v5
    - name: Prepare test image
      run: |
        # some debugging info in case stuff fails
        df -h
        just tests/build
        # delete base ubuntu image as we sometimes run out of diskspace
        lxc image delete "$(lxc image ls -f csv | grep "ubuntu" | awk -F, '{print $2}')"
        sudo lxc image ls
        df -h
    - name: Run tests
      run: just tests/run_test tests/backends/${{ matrix.backend_name }}.sh
