name: Run tests

on:
    push: 
        branches: [main]
    pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run lint and tests tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install test depenencies
      run: sudo apt-get install -y shellcheck
    - name: Run lint
      run: make lint
    - name: Prepare test image
      run: make test-image
    - name: Run tests
      run: make test
